"""empty message

Revision ID: ee995b49947f
Revises: 
Create Date: 2021-02-09 10:18:28.172015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee995b49947f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('project', 'short_desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'short_desc',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###
